### ISSUE TITLE
Move less specific components over to destinations next

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/rizzo-next#312]
We've done a poor job of figuring out which components should live in which places.

For example, Food and Drink, probably shouldn't be a "component" in Rizzo-Next. Perhaps we could have a list component, that we consume in Destinations Next as a component.

I'm sure there's many things we could separate better.

**Comment by thomasthesecond** [comment]
This is a good resource to help think about how our components should work together: http://bradfrost.com/blog/post/atomic-web-design

**Comment by jcreamer898** [comment]
Love the atomic design idea. Would love @WunderBart's input here too!

**Comment by WunderBart** [comment]
I haven't dived into `rizzo-next`'s code yet, but I'm definitely all for keeping only reusable components here. By reusable I mean anything that can be used in more than one app. So it would be ok to keep `Food & Drink` but only if it's cross-app thingy. If not - :fire: it :smile:

**Comment by jcreamer898** [comment]
On further thought. We're just going to move towards https://github.com/lonelyplanet/backpack-ui and eventually move things like header and footer over there. Rizzo-Next will retire.
