### ISSUE TITLE
Namespace header component

### ISSUE THREAD

**Issue by thomasthesecond** [lonelyplanet/rizzo-next#317]
We've already namespaced the search component for use alongside Rizzo and we should do the same for the header component. This also includes all sub-components of the header; logo, navigation, mobile navigation, sub-navigation, avatar and notification badge.

I also think we should consider renaming `.header` to `.global-header` in order to make it more specific. It will also allow us to use `.header` as a more generic header for things such as articles.

**Comment by jcreamer898** [comment]
How about `.lp-global-header`? Start using that `lp` namespace a bit?

**Comment by thomasthesecond** [comment]
That's what I was thinking. Eventually, I think all components will have `lp-`.

**Comment by jcreamer898** [comment]
Yeah, I want to constantly be thinking of this too... https://github.com/lonelyplanet/rizzo-next/issues/312
