### ISSUE TITLE
Position ads

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/rizzo-next#350]
We need to get the logos on the highlights and article pages positioned correctly.

There are 2 pages that you can see them on with `?dfptest` in the URL.

https://www.lonelyplanet.com/asia/travel-tips-and-articles/animal-islands-seven-places-where-creatures-rule?dfptest

https://www.lonelyplanet.com/africa?dfptest

- [ ] Highlights: Logo in with the Love Letter
- [ ] Highlights: Logo in the Masthead
- [ ] Articles: Logo next to the author

**Comment by jcreamer898** [comment]
@thomasthesecond I think I screwed the positioning of the small leaderboard ads up possibly, not entirely sure, but check this out... http://d.pr/i/danU

**Comment by jcreamer898** [comment]
Could be from this... https://github.com/lonelyplanet/rizzo-next/commit/ee38cc2c5d216ff2e4309062fec7f2919e9983ff#diff-3fe14ff70959b9a5bf372ea181990fcaR35

**Comment by thomasthesecond** [comment]
Ok no worries, I'll check it out.
