### ISSUE TITLE
Use ITCSS principles for managing (S)CSS

### ISSUE THREAD

**Issue by thomasthesecond** [lonelyplanet/rizzo-next#428]
http://csswizardry.net/talks/2014/11/itcss-dafed.pdf

Essentially, ITCSS follows the these principles:

- generic to specific
- far-reaching to localized
- low specificity to high specificity

and is made up of the following parts in this order:

- **Settings**: Global variables, config switches
- **Tools**: Default mixins and functions
- **Generic**: Ground-zero styles (Normalize.css, resets, box-sizing)
- **Base**: Unclassed HTML elements (type selectors)
- **Objects**: Cosmetic-free design patterns
- **Components**: Designed components, chunks of UI
- **Trumps**: Helpers and overrides

We may want to modify this to fit our current workflow and structure, but I think it will greatly improve our codebase.

This issue can go along with #312.

**Comment by jcreamer898** [comment]
Looks awesome.
