### ISSUE TITLE
Typescript or Flow?

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/rizzo-next#495]
It could potentially help us implement our styleguide, and would assist as the components grow to utilize a type system. Keyword *potentially*.

https://www.reddit.com/r/javascript/comments/39cere/typescript_vs_flow_results_from_our_investigation/

Let's chat about it, and consider if it's a good or bad idea... 

GO

**Comment by jcreamer898** [comment]
The reason I like the idea is, we're already transpiling w/ Babel from ES2015, etc to ES5, so in my mind the extra annotations could only help as long as they truly are helping. 

ESLint et al are great tools, but don't do as good at catching certain types of bugs.

**Comment by jcreamer898** [comment]
This is the one that gets me as a CON of Flow…
> IDE integration isn't nearly as good as TypeScript right now

**Comment by thomasthesecond** [comment]
Based on that article alone, flow sounds like it might be better for us, specifically with React. But I’m open to either.

**Comment by nicrocs** [comment]
Yeah, the cons of TypeScript seem much worse than the cons of Flow. Figuring out imports and not committing compiled files seems like a real barrier to entry to me.

**Comment by jcreamer898** [comment]
If we do this, it'll be flow probably.
