### ISSUE TITLE
navigation__link causing unwanted menu trigger (UX)

### ISSUE THREAD

**Issue by WunderBart** [lonelyplanet/rizzo-next#553]
It's not a bug, it just causes inconvenience for some users (we actually had a [complaint about it](https://www.lonelyplanet.com/thorntree/permalink/post/22206745)). I think the hover area shouldn't take 100% of the navbar height. It indeed is a bit too triggery.

![screenshot 2016-09-01 15 06 57](https://cloud.githubusercontent.com/assets/1451471/18169399/406312d8-705a-11e6-9e23-660fb4fdcc37.png)

**Comment by nidalaa** [comment]
@WunderBart @jcreamer898 what are the chances to make it done? We should come back to user with some status update :)

**Comment by WunderBart** [comment]
@thomasthesecond @jcreamer898 this might be a bit more serious than I thought (unless IE9 != serious :trollface:).

I've just weaved my cursor over IE9 a bit and this is what I got:

![mnimouse subnav ux issue](https://cloud.githubusercontent.com/assets/1451471/18991981/0c1a77ea-871c-11e6-82ce-4cbb8bf283bc.gif)

Can we treat it as a bug please? We think this can seriously cause bad experience for some old-school TT users.

**Comment by thomasthesecond** [comment]
I can take some time today to look at this.

**Comment by nidalaa** [comment]
Thanks guys! 🙇

**Comment by thomasthesecond** [comment]
@bart @nidalaa I believe this issue has been fixed. I tested it in IE9 via Browerstack, but can you also check it out? If it looks good, then you should be good to bump Rizzo Next in Community.
