### ISSUE TITLE
Shop's lp logo should send user back to homepage

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo-next#554]
User Story
As a user you should be directed back to the homepage when clicking on the LP logo in Shop. 

Acceptance Criteria
- [x] LP logo in shop header should link directly to main homepage.

Other info:
- Due to rizzo-next using relative urls in links everywhere,
- See simliar issue recently closed https://github.com/lonelyplanet/search/issues/191

**Comment by laserchicken** [comment]
fixed
