### ISSUE TITLE
window.lp.analytics.send() being called when moving from DN to POI Restaurant pages.

### ISSUE THREAD

**Issue by PamelaDornan** [lonelyplanet/rizzo-next#688]
On destination next pages (ex Paris or San Francisco) when a user clicks on one of the featured POI restaurant tiles and moves to restaurant POI page, a double pageview gets pushed to GA.  I think this is because the AJAX GTM function is being pinged and the POI page is rendered by an actual page refresh.

Can someone pull out the logic that is calling window.lp.analytics.send() when moving from a destination next page to a POI restaurant page.

Thank you and let me know if you have any questions!

**Comment by jcreamer898** [comment]
This _should_ be fixed now, can you confirm @PamelaDornan?

**Comment by egdelwonk** [comment]
@PamelaDornan can you please confirm if this is correct?
