### ISSUE TITLE
[EMERGENCY] No `Account` section in responsive version of global nav

### ISSUE THREAD

**Issue by nidalaa** [lonelyplanet/rizzo-next#725]
🔥  🔥 🔥 
 After last changes in global nav I cannot see TT under the profil-avatar nav (only responsive design, desktop is ok).

👇  new global nav responsive

<img width="328" alt="screen shot 2017-07-19 at 09 52 48" src="https://user-images.githubusercontent.com/7466903/28372897-d0868c38-6c98-11e7-8a6a-ff1732c1921b.png">

👇  old global nav responsive 
<img width="325" alt="screen shot 2017-07-19 at 09 53 36" src="https://user-images.githubusercontent.com/7466903/28372949-ef3acbc6-6c98-11e7-8d75-bfea6c21f98c.png">

👇  new global nav desktop

<img width="472" alt="screen shot 2017-07-19 at 09 55 01" src="https://user-images.githubusercontent.com/7466903/28372984-0f0a5c32-6c99-11e7-9463-65aa03fd275a.png">

👇 old  global nav desktop

<img width="469" alt="screen shot 2017-07-19 at 09 55 38" src="https://user-images.githubusercontent.com/7466903/28373001-1b82a23a-6c99-11e7-812b-b5fcac902919.png">

**Comment by nidalaa** [comment]
in order to spam all of you :D
@nickfranciosi @jcreamer898 
@bpotterbaum @arielcamus @chrissysievers

**Comment by thomasthesecond** [comment]
I was going to jump into this, but I think it needs input from UI/UX.

**Comment by nidalaa** [comment]
Thank you @thomasthesecond, I really appreciate it :)

**Comment by thomasthesecond** [comment]
I got some UX direction on this. Jumping back on it.

**Comment by thomasthesecond** [comment]
On lpstaging.com now
