### ISSUE TITLE
Bump rizzo-next in all apps to add "Lists" to main navigation for logged in user

### ISSUE THREAD

**Issue by nickfranciosi** [lonelyplanet/rizzo-next#753]
also needed for user id in dataLayer

- [x] copilot
- [x] dotcom-video
- [x] dotcom-poi
- [x] dotcom-profile
- [x] wp-travel-news-fe
- [x] dotcom-connect
- [x] destinations-next
- [x] rizzo legacy / marketing / guides / trips

**Comment by nickfranciosi** [comment]
@laserchicken would you mind bumping the last legacy items listed next week? Let me know if you don't have time. thanks!

**Comment by laserchicken** [comment]
done
