### ISSUE TITLE
Can't open user menu on iPad

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/rizzo-next#765]
Tapping the avatar on iPad takes you to a user's profile, and does not open the user nav items.

https://d.pr/v/dOJTal

**Comment by nickfranciosi** [comment]
@bpotterbaum confirm that we are holding off on this until global nav update?
the other option was to make the avatar always open up the menu and have a "Profile" link in the menu.

**Comment by bpotterbaum** [comment]
I would still like to get this update in before the global nav project.

**Comment by nickfranciosi** [comment]
lets go with the option to  make the avatar always open up the menu and have a "Profile" link in the menu.

**Comment by shawncothran** [comment]
I changed the avatar from a link to a span, but... If the user is logged in there is already a link to "Lists" (which is just /profile/:username), should we rename it, duplicate it with another link saying profile, or leave it as is?
```
    {{#if user.connect}}
    <li class="sub-navigation__item">
       <a class="sub-navigation__link" href="{{user.publicProfileLink}}/lists">Lists</a>
    </li>
    {{/if}}
```

**Comment by shawncothran** [comment]
@bpotterbaum ^^

**Comment by bpotterbaum** [comment]
Uh, I don't understand the question?
