### ISSUE TITLE
Cookie banner appearing on Mobile

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo-next#797]
Cookie banner is appearing on Mobile and it's undismissable because the `OK` button is being cut off. 

![image](https://user-images.githubusercontent.com/20303852/32793035-6ec2c61c-c92a-11e7-8e10-3fcb9dcc7bd6.png)

**Comment by nickfranciosi** [comment]
@chrissysievers is that a bug?

**Comment by chrissysievers** [comment]
@WunderBart we never see this banner in the US, so we're always unclear on what the root problem is. Is the bug:

(1) the banner is cutting off at "You can update your..." and not displaying the entire message?

or

(2) the banner repeatedly appears even after you click out of it?

Feel free to edit the original issue to be more specific.

**Comment by WunderBart** [comment]
@chrissysievers, I've updated the description. It looks like a css bug, @nickfranciosi.
